Repository SanaTameem/book-an-appointment-front-end, pull requests merged in 2023-11, with the labels that each got.

#5 Main Page Implementaion
  package-lock.json
  package.json
  src/assets/css/carousel.css
  src/components/cars/CarItem.jsx
  src/components/cars/MainPage.jsx
  src/redux/features/carsSlice.js
Labels: Massam's Task

#6 Details page
  src/App.js
  src/assets/css/carousel.css
  src/assets/css/index.css
  src/components/Navbar.jsx
  src/components/cars/CarDetails.jsx
  src/components/cars/CarItem.jsx
  src/components/cars/MainPage.jsx
Labels: Sana's Task

#7 Car reservation
  package.json
  src/App.js
  src/assets/css/index.css
  src/components/cars/AddCarsForm.js
  src/components/cars/CarDetails.jsx
  src/components/cars/CarItem.jsx
  src/components/cars/MainPage.jsx
  src/components/cars/SkeletonLoading.jsx
  src/components/reservations/Reservations.jsx
  src/redux/features/carsAction.js
  src/redux/features/carsSlice.js
  src/redux/features/reservationAction.js
  src/redux/features/reservationSlice.js
Labels: Melkamu's Task

#8 Delete Cars
  src/assets/css/carousel.css
  src/assets/css/index.css
  src/components/cars/AddCarsForm.js
  src/components/cars/DeleteCar.jsx
  src/components/cars/MainPage.jsx
  src/redux/features/carsAction.js
  src/redux/features/carsSlice.js
Labels: Sana's Task

#9 Feature/reservation list
  src/App.js
  src/components/Navbar.jsx
  src/components/reservations/Reservations.jsx
  src/components/reservations/myReservation.jsx
  src/components/reservations/reservationList.jsx
  src/components/reservations/reserveCar.jsx
  src/redux/features/carsAction.js
  src/redux/features/reservationAction.js
  src/redux/features/reservationSlice.js
  src/redux/store.js
Labels: Melkamu's Task

#10 implementing Logout action
  src/components/Navbar.jsx
Labels: Melkamu's Task

#11 App Responsiveness
  MIT.md
  README.md
  src/App.js
  src/assets/css/carousel.css
  src/assets/css/index.css
  src/components/Login.js
  src/components/Navbar.jsx
  src/components/Register.js
  src/components/auth/SignInForm.js
  src/components/cars/AddCarsForm.js
  src/components/reservations/Reservations.jsx
  src/components/reservations/myReservation.jsx
  src/components/reservations/reservationList.jsx
  src/components/reservations/reserveCar.jsx
  src/redux/features/reservationAction.js
Labels: Sana's Task, Massam's Task
